-- SAS.SCORE_CLID_INFO_DATA_RP
REP_DATE date,
REP_CLID integer,
REP_INN char(12),
REP_BDATE date,
REP_SEX char(1),
REP_FL_AG char(1),
REP_FL_BELIEVE char(1),
REP_FL_VIP char(1),
REP_RES char(4),
CL_GEO_BRNM char(4),
REP_CR_ST integer,
REP_BLACK_ST integer,
REP_IDENT char(1),
DATE_IDENT date,
LDAP_IDENT char(12),
BNMN_IDENT char(2),
FL_DEPOS char(1),
FL_KOPL char(1),
FL_GOLD char(1),
FL_PPNET char(1),
FL_JUR_ACC char(1),
FL_AVTO char(1),
FL_ESTATE char(1),
FL_ZP char(1),
FL_PENS char(1),
FL_STUD char(1),
FL_SOC char(1),
FL_P24 char(1),
FL_MOBB char(1),
FL_SMSI char(1),
FL_CR_PAN char(1),
FL_MINI char(1),
FL_METRO char(1),
FL_ACT_RASR char(1),
FL_PERS_CR char(1),
FL_RASR char(1),
FL_G_MPH char(1),
FL_Y_MPH char(1),
FL_G_MAIL char(1),
FL_Y_MAIL char(1),
FL_G_PH char(1),
FL_Y_PH char(1),
QTY_CHLD integer,
QTY_CHLD_16 integer,
CL_FAM_ST char(12),
CL_EDU char(3),
CL_OFF_POS char(11),
CL_OWN_TYPE char(17),
CL_INDUSTR char(15),
CL_SOC_ST char(11),
CL_AUTO_EX char(1),
CL_ESTATE_TYPE char(17),
CL_WORK_YEARS integer,
CL_WORK_MONTH integer,
CL_CCY_ZP char(3),
CL_AMT_ZP integer,
CL_CCY_DOP char(3),
CL_AMT_DOP integer,
CL_PHOTO_1 char(1),
CL_PHOTO_2 char(1),
CL_PHOTO_3 char(1),
CL_PHOTO_4 char(1),
CL_TRIM char(1),
CL_RTRIM char(1),
FL_PLATINUM char(1),
FL_SIGNIA char(1),
FL_INFINITE char(1),
FL_SEYF char(1),
FL_TOPL char(1),
FL_RASCH char(1),
FL_DIR_UCH char(1),
CL_SUPR char(1),
CL_BLIZ char(1),
CL_PERS char(1),
REP_LANG char(2),
FL_FACT_ADR char(1),
FL_JUR_ADR char(1),
FL_PASSP char(1),
FL_ANKETA_IDENT char(1),
LAT_CL numeric(108),
LON_CL numeric(108),
DATE_CLID date,
FL_4P char(1),
FL_DOC_PROFIT char(1),
REP_POPULATION numeric(152),
FL_RLCL char(1),
REP_RLCL_MAXCRIT char(3),
REP_RLCL_LIMIT_36 numeric(152),
REP_RLCL_LIMIT_60 numeric(152),
REP_RLCL_LIMIT_120 numeric(152),
REP_RLCL_MAXPAY numeric(152),
FL_PENS_DOC char(1),
DATE_PENS_DOC date,
ADDR_COUNTRY_ID char(14),
ADDR_AREA_ID char(14),
ADDR_REGION_ID char(14),
ADDR_CITY_ID char(14),
FL_INTERNET_PAN char(1),
FL_PHIN_PH char(1),
REP_LIMIT numeric(152),
LIMIT_TYPE_GROUP char(20),
REP_RLCL_INCOME numeric(152),
REP_RLCL_TYPE_CLIENT char(20),
REP_RLCL_BBN_BNMN char(2),
REP_RLCL_LIMIT_12 numeric(152),
ADDR_ZIP char(12),
FL_PRV_HOUSE char(1),
FL_LUCKY_CODE char(1),
FL_FRNG_PASSP char(1),
FL_TRAN_FLMN_3M char(1),
AMT_VEGA_VOLIA_3M numeric(152),
AMT_UKRT_INTERT_3M numeric(152),
CLID_WORK_OKPO char(35),
REP_CLID_WORK_JUR integer,
CLID_WORK_NAME char(255),
FL_SEAMAN char(1),
FL_FORMAT_PH char(1),
FL_MOTHER_NAME char(1),
CLID_ITOG_PROFIT numeric(152),
CLID_STATE char(1),
FL_INSUR_NS char(1),
FL_INSUR_TI char(1),
FL_INSUR_NB char(1),
FL_INSUR_OS char(1),
FL_INSUR_CAS char(1),
FL_ACD char(1),
PAYSTP_AMT_ALL numeric(152),
QTY_DEPOS integer,
AMT_DEPOS numeric(152),
DATE_FIRST_DEPOS date,
AMT_DEPOS_KOP numeric(152),
P24_DATREG date,
P24_LEDATE date,
MOB_PHN_OPER char(6),
FL_REL_LINK char(1),
FL_EMPLOYEE char(1),
FL_EMPLOYEE_STATE char(1),
FL_RP char(1),
FL_PP char(1),
FL_MICRO char(1),
FL_BONJ char(1),
FL_JUNC char(1),
FL_AGENT char(1),
FL_CURSB char(1),
FL_EXPR char(1),
FL_SAFB char(1),
FL_CREDV char(1),
FL_TRANS char(1),
FL_PAYPH char(1),
FL_TOPP char(1),
FL_CREDP char(1),
FL_EMPPOL char(1),
FL_DEPRUK char(1),
FL_RIDER char(1),
FL_SOCIALM char(1),
FL_SOCIALU char(1),
FL_CREDB char(1),
FL_AUTORP char(1),
FL_PAYPHONE char(1),
FL_PAYPRJ char(1),
FL_TRANP char(1),
FL_TRANC char(1),
FL_SEACM char(1),
FL_PAYPART char(1),
FL_RPMOB char(1),
FL_RPUTIL char(1),
FL_RPINS char(1),
FL_RPOTH char(1),
FL_RPCP24 char(1),
FL_WRLC char(1),
FL_SOCIALR char(1),
FL_SOCIALO char(1),
FL_LIQPAY char(1),
FL_TOPSC char(1),
FL_RPDEP char(1),
FL_PPTSO char(1),
FL_PPTTSO char(1),
FL_MOBEQI char(1),
FL_CREDJ char(1),
FL_PRIORPASS char(1),
REP_AGE integer,
FL_POTENCIAL_VIP_TT char(1),
FL_ACTIVE char(1),
BBN_BNMN_ACTUAL char(2),
FL_PAN_PATRIOT char(1),
PROS_D_OTHER_BANK integer,
AMT_PROS_OTHER_BANK numeric(152),
FL_INKASSO char(1),
DATE_LAST_PHOTO date,
QTY_PHONE integer,
QTY_MOB_PHONE integer,
QTY_HOME_PHONE integer,
QTY_DEL_PHONE integer,
QTY_G_PHONE integer,
FL_BLACK_PHONE char(1),
FL_ADDR_JUR_IS_ADDR_FACT char(1),
QTY_RELTV_LINK integer,
MAX_PROS_D_RELTV integer,
FL_PROS_RELVT_OTHER_BANK char(1),
FL_BLACK_LIST_RELTV char(1),
QTY_CREDIT integer,
QTY_PROS_REF integer,
FL_DEFAULT_1 char(1),
FL_DEFAULT_2 char(1),
FL_DEFAULT_3 char(1),
FL_REGP_CREDIT char(1),
NPS_DEPOS integer,
NPS_KOPL integer,
NPS_ZP integer,
NPS_CR_PAN integer,
NPS_P24 integer,
NPS_BANK integer,
NPS_PENS integer,
NPS_INTERNET_TRAN integer,
NPS_P24_MOB integer,
NPS_GOLD integer,
FL_FRNG_PASSP_ACTUAL char(1),
CL_AUTO_EX_ACTUAL char(1),
EMAIL_OPERATOR char(40),
FL_PAN_PATRIOT_VISA char(1),
FL_PAN_PATRIOT_MC char(1),
ID_VK char(75),
AGE_REG_SN integer,
QTY_FRIENDS_SN integer,
FL_PH_SN char(2),
FL_SKYPE_SN char(2),
FR_AVG_AGE integer,
FR_HIGH_EDU numeric(102),
FR_HOMETOWN numeric(42),
FR_EKB numeric(52),
FR_VIP numeric(52),
FR_PROSR numeric(52),
FR_FOREIGN numeric(52),
FR_PB numeric(52),
QTY_RELATIVES integer,
VK_REGISTR_YEAR integer,
UNIVER_COUNTRY char(50),
UNIVER_CITY char(50),
PL_MOBILE char(2),
PL_IPHONE char(2),
PL_IPAD char(2),
PL_ANDROID char(2),
PL_WPHONE char(2),
PL_WINDOWS char(2),
PL_WEB char(2),
SN_DEACTIVATED char(15),
PL_LAST_SEEN_DATE timestamp,
FR_AVG_ID integer,
FR_ID_AGE_DEV integer,
AGE_GR_AVG_ID integer,
AGE_GR_ID_DISP integer,
AGE_GR_ID_DEV integer,
SN_TIME_FROM_NW integer,
FR_OPPOS_SEX numeric(52),
VISIT_SHENGEN char(2),
VISIT_ASIA char(2),
VISIT_AFRICA char(2),
VISIT_EUROPE char(2),
VISIT_AUSTRAL char(2),
REP_AGE_CATEGORY integer,
REGION_CATEGORY integer,
MEAN_ID numeric(150),
MEAN_REGION_ID numeric(150),
MEAN_FRIENDS_ID numeric(150),
MEDIAN_ID numeric(150),
MEDIAN_FRIENDS_ID numeric(150),
MEDIAN_REGION_ID numeric(150),
DISP_REGION_ID numeric(150),
AVG_FR_OF_FR_NUMB integer,
AVG_FR_OF_FR_DEVIAT numeric(155),
DISP_ID numeric(150),
DENSITY_ID numeric(104),
AVG_FR_AGE_CATEG integer,
DEVIAT_AVG_FR_AGE_CATEG numeric(104),
SMPH_OS char(15),
FL_MAR_ST char(2),
FL_OTHER_SN char(2),
FL_NICK char(2),
SYMB_ABOUT integer,
FL_VID_MORE_AUD char(2),
AVG_PHOTO_ALBUM integer,
SMOKING_POS char(2),
ALCOHOL_POS char(2),
FL_RELIG char(2),
FL_SITE char(2),
FL_ENTR_BY_MOB char(2),
FOLLOW_TO_FR integer,
FL_DIF_UNIV_CITY char(2),
SELL_AUTO char(2),
ACC_JOB_SITE char(2),
PAGES_TO_AVG numeric(102),
NOTES_TO_AVG numeric(102),
PHOTOS_TO_AVG numeric(102),
FILL_TXT_FLD integer,
FL_CORRECT_NAME char(2),
FL_PB_GR char(2),
FL_REG_PRIOR_PEAK char(2),
CAN_RECEIVE_MSG char(1),
CALC_DATE date,
ABROAD char(2),
COUNTR_VISIT integer,
MAIDAN_GROUPS char(1),
ANTIMAIDAN_GROUPS char(1),
MAIDAN_GROUPS_CNT integer,
ANTIMAIDAN_GROUPS_CNT integer,
FR_MAIDAN numeric(204),
FR_ANTIMAIDAN numeric(204),
FR_UNI numeric(204),
FR_DEPOSIT numeric(204),
FR_GOLD numeric(204),
FR_RUSSIA numeric(204),
LAST_SEEN_TIME timestamp,
FIRST_PROD_DATE date,
FIRST_PROD_TYPE integer,
QTY_G_PROD integer,
ECA_BRNM2_REAL char(4),
AVG_UTIL_6M numeric(152),
MIN_DATESTART_ALL_CRCARDS char(10),
MIN_DATEFIRST_DB_CRCARDS char(10),
QTY_EXAGE1_3Y integer,
QTY_EXAGE30_3Y integer,
QTY_EXAGE60_3Y integer,
QTY_MONTH_TO_LATE_FEE_6M integer,
QTY_MONTH_TO_MAX_BAL_6M integer,
QTY_MONTH_TO_ZP_INC_AMT integer,
QTY_MONTH_BAL_PEN1_6M integer,
QTY_MONTH_BAL_PEN2_6M integer,
QTY_MONTH_OVER_6M integer,
QTY_MONTH_OVER_PAYM_6M integer,
QTY_MONTH_CR_TO_BAL7PERC_6M integer,
QTY_MONTH_TARG_INC_7M integer,
CLID_UTIL_CURR integer,
FL_BAL_DEPT_LESS_MINPAY_CURR char(1),
FL_SALARY_AMT_CURR_MONTH char(1),
MAX_BAL_CRCARDS_6M numeric(152),
QTY_DAYS_OF_DELAY_CRCARDS_CURR integer,
AMT_DELAY_CRCARDS_CURR numeric(152),
QTY_MAX_DAYS_OF_DELAY_3Y integer,
QTY_MAX_DAYS_OF_DELAY_6M integer,
AMT_MAX_DELAY_6M numeric(152),
RAT_MAX_BALDEBT_TO_CRLIM_6M numeric(152),
MAX_LIM_UTIL_6M numeric(152),
QTY_MONTH_REF_AGE numeric(152),
QTY_MONTH_MAX_UTIL_6M numeric(152),
RAT_BALDEBT_TO_BALALL_CURR numeric(152),
RAT_CURRLIM_TO_STARTLIM numeric(152),
REP_BAL_CR numeric(152),
REP_BAL_ALL_CR numeric(152),
AMT_DEBT_CR numeric(152),
AMT_MINPAY_CR_CURR_MONTH numeric(152),
AMT_CR_TO_SALARY_CURR_MONTH numeric(152),
REP_LIMIT_CR numeric(152),
QTY_ALL_REF_NOT_PB_UBKI integer,
QTY_MONTH_MAXDTSTART_REFS_UBKI integer,
QTY_MAX_MONTH_ALLEX_UBKI integer,
AMT_MAX_PROSR90_UBKI integer,
QTY_FPSPD_UBKI integer,
AMT_MAX_PROSR60_UBKI integer,
QTY_QUERY_KI_6M_UBKI integer,
QTY_QUERY_KI_ALL_UBKI integer,
QTY_MONTH_MINDTSTART_REFS_UBKI integer,
QTY_ALL_EX10_30_3M_UBKI numeric(152),
QTY_ALL_EX30_60_UBKI numeric(152),
QTY_ALL_EX60_90_UBKI numeric(152),
QTY_ALLE_X90_UBKI numeric(152),
QTY_ALL_FPD_UBKI numeric(152),
QTY_ALL_EX60_UBKI numeric(152),
AMT_ALL_DEBT_UBKI numeric(152),
AMT_ALL_EX_UBKI numeric(152),
AMT_MAND_PAYM_UBKI numeric(152),
QTY_ALL_EX30_60_6M_UBKI numeric(152),
QTY_ALL_EX60_90_6M_UBKI numeric(152),
QTY_ALL_EX90_6M_UBKI numeric(152),
QTY_CLOSE_REFS_UBKI integer,
ID_OK char(50),
QTY_FRIENDS_SN_OK integer,
FR_EKB_OK numeric(52),
FR_VIP_OK numeric(52),
FR_PROSR_OK numeric(52),
FR_PB_OK numeric(52),
FR_UNI_OK numeric(204),
FR_DEPOSIT_OK numeric(204),
FR_GOLD_OK numeric(204),
FR_OK_FOREIGN numeric(106),
FR_HOMETOWN_OK numeric(106),
FR_AVG_AGE_OK numeric(106),
FR_MALE_OK numeric(106),
FR_FEMALE_OK numeric(106),
FR_HIGH_EDU_OK numeric(106),
UNIVER_COUNTRY_OK char(150),
UNIVER_CITY_OK char(150),
FR_OPPOS_SEX_OK numeric(106),
FL_DIF_UNIV_CITY_OK char(1),
FL_CORRECT_NAME_OK char(1),
FR_RUSSIA_OK numeric(106),
JOB_MARK_OK char(1),
FR_NATIVE_TO_FOREIGN numeric(106),
FR_JOBLESS_OK numeric(106),
FL_STUDENT_OK char(1),
FR_GOOD_FR numeric(106),
FL_DIF_JOB_CITY_OK char(1),
FL_DIF_JOB_COUNTRY_OK char(1),
FL_MEGAPOLIS char(1),
PAGE_FIT numeric(102),
QTY_GOOD_FR numeric(104),
NOT_P_NUM char(1),
FR_KOPL numeric(104),
FR_P24 numeric(104),
FR_RP numeric(104),
FL_STUDENT_VK char(1),
QTY_ACC integer,
QTY_SELF_INFO integer,
FL_NATIVE numeric(104),
I_GIRL char(1),
FL_PATRONYMIC char(1),
GOLD_YONG char(1),
QTY_VNZ integer,
FL_LAW_HIDE char(1),
COUNTRY_SN char(70),
CITY_SN char(70),
QTY_FR_BAD numeric(104),
QTY_REALTY_SALE integer,
QTY_SALE integer,
QTY_RELATIVES_FRIEND numeric(104),
UNI_RANK char(1),
QTY_AVTO_SALE integer,
QTY_AVTO_SOLD integer,
MISSING char(1),
FR_WITH_SMARTPHONE numeric(104),
HIGH_EDU char(1),
FOREIGN_REL char(1),
SCHOOL_COUNTRY char(100),
SCHOOL_CITY char(100),
PRIVACY integer,
FL_DIF_SCHOOL_COUNTRY char(1),
FL_DIF_SCHOOL_CITY char(1),
MAIDEN_NAME char(1),
POLITICS char(1),
LIFE_MAIN integer,
PEOPLE_MAIN integer,
FL_VIBER char(1),
MOB_OS_NAME_P24_ENTRY char(20),
AMT_DEBT_ENGINE numeric(152),
AMT_PROS_ENGINE numeric(152),
W_PC numeric(152),
FL_SB_ENGINE char(1),
PROS_D_ENGINE integer,
QTY_D_P24_REG integer,
QTY_D_LAST_PHOTO integer,
QTY_D_FIRST_PROD integer,
QTY_D_START_ALL_CRCARD integer,
QTY_D_FIRST_DB_CRCARD integer,
DATE_FIRST_KDV_CEL date,
DATE_FIRST_KDV_WITHOUT_CEL date,
QTY_D_FIRST_KDV_CEL integer,
QTY_D_FIRST_KDV_WITHOUT_CEL integer,
RESIDENCE_REGION char(30),
RESIDENCE_CITY_TYPE char(10),
RESIDENCE_ECONOMIC_AREA char(20),
DIST_TO_CITY_CENTRE integer,
INCOME_GROUP_TYPE integer,
QTY_LINK_AUTO integer,
RAT_CLID_AUTO_TO_LINK_ALL numeric(154),
RAT_CLID_AUTO_TO_LINK_COHAB numeric(154),
RAT_CLID_BAD90_TO_LINK_COHAB numeric(154),
RAT_CLID_BAD90_TO_LINK_NEI numeric(154),
RAT_CLID_BLACK21_TO_LINK_ALL numeric(154),
RAT_CLID_BLACK_LIST_TO_LINK_NEI numeric(154),
RAT_CLID_BLACK_LIST_TO_LINK_ALL numeric(154),
RAT_QTY_CHDL_TO_LINK_NEI numeric(154),
RAT_QTY_CHDL_TO_LINK_PHONE numeric(154),
QTY_LINK_H_EDU integer,
RAT_CLID_H_EDU_TO_LINK_ALL numeric(154),
QTY_CLID_H_EDU_FROM_LINK_COHAB integer,
RAT_CLID_H_EDU_TO_LINK_COHAB numeric(154),
RAT_CLID_H_EDU_TO_LINK_NEI numeric(154),
QTY_CLID_H_EDU_TO_LINK_FAM integer,
RAT_CLID_H_EDU_TO_LINK_FAM numeric(154),
QTY_CLID_EDU_TO_LINK_COHAB integer,
RAT_CLID_FAMST_DIV_TO_LINK_NEI numeric(154),
QTY_LINK_FAMST_MAR integer,
RAT_CLID_FAMST_MAR_TO_LINK_ALL numeric(154),
RAT_CLID_FAMST_MAR_TO_LINK_COHAB numeric(154),
RAT_GROUP_OTHER_TO_LINK_ALL numeric(154),
RAT_LINK_NEI_TO_LINK_DRFO numeric(154),
RAT_LINK_FAM_TO_LINK_DRFO numeric(154),
RAT_LINK_PHONE_TO_LINK_ALL numeric(154),
RAT_LINK_PHONE_TO_LINK_EKB numeric(154),
QTY_LINK_PHONE integer,
QTY_LINK_SRC_EKB integer,
RAT_SRC_EKB_TO_LINK_ALL numeric(154),
RAT_SRC_DRFO_TO_LINK_ALL numeric(154),
RAT_SRC_SOCLINK_TO_LINK_ALL numeric(154),
QTY_LINK_ATO_CLID integer,
QTY_LINK_CRIMEA_CLID integer,
RAT_LINK_VIP_CLID_GROUP_RELAT numeric(154),
RAT_LINK_VIP_CLID_GROUP_OTHER numeric(154),
RAT_LINK_VIP_CLID_SRC_EKB numeric(154),
RAT_LINK_VIP_CLID_SRC_DRFO numeric(154),
RAT_LINK_VIP_CLID_SRC_PAYMENTS numeric(154),
RAT_LINK_VIP_CLID_SRC_CONTR_AG numeric(154),
RAT_LINK_VIP_CLID_TO_LINK_GUAR numeric(154),
RAT_LINK_VIP_CLID_TO_LINK_COHAB numeric(154),
RAT_LINK_VIP_CLID_TO_LINK_TRANS numeric(154),
AMT_CR_DB_CREDIT_CARD_3M numeric(152),
ZP_REP_TYPE char(4),
AVG_AMT_ZP numeric(152),
QTY_DEPOS_FOREIGN_CCY integer,
QTY_FAMILIAR_DRFO integer,
QTY_LINK_ALL integer,
AMT_MONTH_INCOME_FORECAST numeric(152),
LOST_CLIENT_WITH_LIMIT char(1),
BEHAV_CR_PAN_SCORE_AMT numeric(152),
FIN_PHONE_WEIGHT integer,
PHONE_MAX_WEIGHT integer,
PB_SITE_USER char(1),
FRQ_VISIT integer,
PROD_FAVOR_APP char(1),
PROD_FAVOR_DEPOS char(1),
PROD_FAVOR_UNI char(1),
PROD_FAVOR_KOPIL char(1),
PROD_FAVOR_AUTOCREDIT char(1),
PROD_FAVOR_HOUSE_CREDIT char(1),
PROD_FAVOR_PAYM_PART char(1),
PROD_FAVOR_PAY_CARD char(1),
PB_NEWS char(1),
ENTRY_TIME char(15),
PROD_FAVOR_BONUS_PLUS char(1),
PROD_FAVOR_PLANETA_AVTO char(1),
USER_OS_WINDOS char(1),
USER_OS_LINUX char(1),
USER_OS_MACOS char(1),
USER_BROWSER_CHROME char(1),
USER_BROWSER_MOZILLA char(1),
USER_BROWSER_SAFARI char(1),
USER_BROWSER_OPERA char(1),
USER_BROWSER_EXPLORER char(1),
QTY_DAYS_PER_MONTHS integer,
PROD_FAVOR_TICKETS char(1),
MOB_PLATFORM_IOS char(1),
MOB_PLATFORM_ANDROID char(1),
USER_PROVIDER char(255),
USES_ADBLOCK char(1),
FL_WEB_USER char(1),
FRQ_VISIT_7D integer,
FRQ_VISIT_14D integer,
FRQ_VISIT_60D integer,
FRQ_VISIT_120D integer,
FRQ_VISIT_SHOP_7D integer,
FRQ_VISIT_SHOP_14D integer,
FRQ_VISIT_SHOP_30D integer,
FRQ_VISIT_SHOP_60D integer,
FRQ_VISIT_SHOP_120D integer,
FRQ_VISIT_PRICE_AGGR_7D integer,
FRQ_VISIT_PRICE_AGGR_14D integer,
FRQ_VISIT_PRICE_AGGR_30D integer,
FRQ_VISIT_PRICE_AGGR_60D integer,
FRQ_VISIT_PRICE_AGGR_120D integer,
FRQ_SESSIONS_7D integer,
FRQ_SESSIONS_14D integer,
FRQ_SESSIONS_30D integer,
FRQ_SESSIONS_60D integer,
FRQ_SESSIONS_120D integer,
FRQ_BASKET_30D integer,
FRQ_BASKET_ALL integer,
QTY_DAYS_LAST_VISIT integer,
FL_FILMS char(1),
FRQ_ADV_CLICKS integer,
QTY_DIFF_CITIES integer,
FRQ_FOREIGN_VISITS integer,
FL_SMARTPHONE char(1),
DEVICE_MODEL char(60),
FRQ_VISIT_TOURISM integer,
FRQ_VISIT_AUTOMOBILE integer,
FRQ_VISIT_BUSINESS_FINANCE integer,
FRQ_VISIT_NEWS integer,
FRQ_VISIT_WEATHER integer,
FRQ_VISIT_BEAUTY_HEALTH integer,
FRQ_VISIT_MOMS integer,
FRQ_VISIT_COOK integer,
FRQ_VISIT_SPORT integer,
FRQ_VISIT_GADGETS integer,
FRQ_VISIT_REAL_ESTATE integer,
FRQ_VISIT_EDUCATION integer,
AVG_SESSION_DEPTH numeric(152),
FRQ_VISIT_COMPARED_TO_LAST_M numeric(152),
USER_LANGUAGE char(4),
VISIT_USA char(1),
FL_BAD_GROUPS char(1),
FL_GOOD_GROUPS char(1),
FL_BAD_ARTISTS char(1),
FL_GOOD_ARTISTS char(1),
QTY_BAD_GROUPS integer,
QTY_GOOD_GROUPS integer,
QTY_BAD_ARTISTS integer,
QTY_GOOD_ARTISTS integer,
PRC_BAD_GROUPS numeric(105),
PRC_GOOD_GROUPS numeric(105),
PRC_BAD_ARTISTS numeric(105),
PRC_GOOD_ARTISTS numeric(105),
AMT_FO numeric(152),
AMT_FO_GROUP smallint,
AMT_MAX_DELAY_HIST numeric(152),
QTY_MAX_DAYS_OF_DELAY_HIST integer,
FO_DELAY_GROUP smallint,
LIM_FO_MAX numeric(152),
LIM_FO_GROUP smallint,
FL_CL_SOC_ST_SING char(1),
FO_DEPOS_ALL char(1),
FO_SOURCES_GROUP smallint,
FO_ASSET_GROUP smallint,
P24_WEB_REG integer,
P24_MOB_REG integer,
FL_CARD_GROUP integer,
CL_SOC_ST_GROUP smallint,
CL_OFF_POS_GROUP smallint,
FL_BUS_ENT smallint,
FL_USA char(1),
FL_NO_UA char(1),
FIN_STAN_BALL integer,
FIN_STAN integer,
FL_DEAD smallint,
FL_HOMELESS smallint,
FL_PSYCHO smallint,
FL_DRUG_TAKER smallint,
FL_CRIMINAL_RECORD smallint,
FL_SWINDLER smallint,
FL_FACEBOOK char(1),
QTY_CHUGAISTER_1M integer,
QTY_CHUGAISTER_3M integer,
QTY_CHUGAISTER_6M integer,
QTY_CHUGAISTER_AL integer,
FL_ENTER_QR_1M char(1),
FL_ENTER_QR_3M char(1),
FL_ENTER_QR_6M char(1),
FL_ENTER_QR_AL char(1),
QTY_INNOVATION_PROD integer,
QTY_IGOV_REQ integer,
ADDR_CITY_ID_REAL char(14),
QTY_P24_FIRST_DD integer,
FL_CSH_OTD_6M char(1),
PRIOR_CHANNEL_INFO char(6),
BALL_BEZOP numeric(152),
BALL_ECONOM_SR numeric(152),
BALL_INNOV numeric(152),
BALL_DOM numeric(152),
BALL_ECONOM_VR numeric(152),
BALL_COMFORT numeric(152),
BALL_MODA numeric(152),
BALL_PROSTOTA numeric(152),
BALL_INTEL numeric(152),
BALL_MIN_OBOROT numeric(152),
I_SEGMENT char(10),
-- from SAS.SCORE_CLID_CRM_DATA_RP
	QTY_OUT_CALL    integer ,    
	QTY_OUT_RECALL  integer ,    
	QTY_OK_OUT_CALL integer ,    
	QTY_OUT_CALL_TA integer ,    
	QTY_SMS integer ,    
	QTY_SMS_TA  integer ,    
	QTY_PC_INCUT    integer ,    
	QTY_OK_PC_INCUT integer ,    
	QTY_PC_INCUT_TA integer ,    
	QTY_ATM_INCUT   integer ,    
	QTY_OK_ATM_INCUT    integer ,    
	QTY_ATM_INCUT_TA    integer ,    
	QTY_TSO_INCUT   integer ,    
	QTY_OK_TSO_INCUT    integer ,    
	QTY_TSO_INCUT_TA    integer ,    
	QTY_P24_INCUT   integer ,    
	QTY_OK_P24_INCUT    integer ,    
	QTY_P24_INCUT_TA    integer ,    
	QTY_OUT_EMAIL   integer ,    
	QTY_DELIV_OUT_EMAIL integer ,    
	QTY_OK_OUT_EMAIL    integer ,    
	QTY_OUT_EMAIL_TA    integer ,    
	QTY_IN_CALL integer ,    
	QTY_SMS_ALL integer ,    
	QTY_SMS_TA_ALL  integer ,    
	QTY_IVR integer ,    
	QTY_OK_IVR  integer ,    
	QTY_IVR_ALL integer ,    
	QTY_OK_IVR_ALL  integer ,    
	QTY_OUT_EMAIL_ALL   integer ,    
	QTY_OK_OUT_EMAIL_ALL    integer ,    
	QTY_OUT_CALL_ALL    integer ,    
	QTY_OUT_CALL_TRY_ALL    integer ,    
	QTY_OK_OUT_CALL_ALL integer ,    
	QTY_OK_PERS_OUT_CALL_ALL    integer ,    
	QTY_IN_CALL_SOFT    integer ,    
	QTY_IN_CALL_ALL_SOFT    integer ,    
	QTY_OUT_CALL_SOFT   integer ,    
	QTY_OUT_CALL_ALL_SOFT   integer ,    
	QTY_OK_OUT_CALL_SOFT    integer ,    
	QTY_OK_OUT_CALL_ALL_SOFT    integer ,    
	QTY_OK_PERS_OUT_CALL_SOFT   integer ,    
	QTY_OK_PERS_OUT_CALL_ALL_SOFT   integer ,    
	QTY_CALL_RELTV  integer ,    
	QTY_CALL_RELTV_ALL  integer ,    
	QTY_CALL_OK_PAY integer ,    
	QTY_CALL_OK_PAY_ALL integer ,    
	QTY_CALL_OK_RELTV_PAY   integer ,    
	QTY_CALL_OK_RELTV_PAY_ALL   integer ,    
	QTY_CALL_NO_PAY integer ,    
	QTY_CALL_NO_PAY_ALL integer ,    
	QTY_CALL_3700_3M    integer ,    
	QTY_CALL_3700   integer ,    
	QTY_CALL_BACK_3M    integer ,    
	QTY_CALL_BACK   integer ,    
	QTY_BOK_3M  integer ,    
	QTY_BOK integer ,    
	QTY_PROMIS_TA_SOFT  integer ,    
	QTY_PROMIS_TA_ALL_SOFT  integer ,    
	QTY_SMS_SOFT    integer ,    
	QTY_SMS_ALL_SOFT    integer ,    
	QTY_IVR_SOFT    integer ,    
	QTY_IVR_ALL_SOFT    integer ,    
	QTY_OUT_EMAIL_ALL_SOFT  integer ,    
	QTY_OK_OUT_EMAIL_ALL_SOFT   integer ,    
	QTY_COME_EXPL_SOFT  integer ,    
	QTY_NOT_COME_EXPL_SOFT  integer ,    
	QTY_COME_EXPL_ALL_SOFT  integer ,    
	QTY_NOT_COME_EXPL_ALL_SOFT  integer ,    
	QTY_REQ_BOK_SOFT    integer ,    
	QTY_DIED_JAIL_SOFT  integer ,    
	QTY_ARMY_ABROAD_SOFT    integer ,    
	QTY_MOBILIZ_ALL_SOFT    integer ,    
	QTY_ATO_ZONE_ALL_SOFT   integer ,    
	QTY_VISITS_ALL_HARD integer ,    
	QTY_CONT_ALL_HARD   integer ,    
	QTY_SMS_PRE_COLLECT_30  integer ,    
	QTY_OK_IVR_PRE_COLLECT_30   integer ,    
	QTY_OUT_OKCALL_PERS_PRECOL_30   integer ,    
	QTY_OK_CROSS_HARD   integer ,    
	QTY_OK_HARD_REMIND  integer ,    
	QTY_OK_HARD_BREACH_PAYM integer ,    
	QTY_OK_HARD_PAYM_REF    integer ,    
	QTY_OK_LEGAL_CLAIM  integer ,    
	QTY_OK_LEGAL_POSTED_CLAIMS  integer ,    
	QTY_OK_LEGAL_PROC_OPEN  integer ,    
	QTY_OK_LEGAL_COURT_DEC  integer ,    
	QTY_OK_LEGAL_OPEN_ENFORC_PROC   integer ,    
	QTY_OK_LEGAL_PL integer ,    
	QTY_HARD_SUCC_EXITS integer ,    
	QTY_OK_HARD_CALL    integer ,    
	QTY_OUT_CALL_MONTH  integer ,    
	QTY_OUT_RECALL_MONTH    integer ,    
	QTY_SMS_MONTH   integer ,    
	QTY_PC_INCUT_MONTH  integer ,    
	QTY_OK_PC_INCUT_MONTH   integer ,    
	QTY_ATM_INCUT_MONTH integer ,    
	QTY_OK_ATM_INCUT_MONTH  integer ,    
	QTY_TSO_INCUT_MONTH integer ,    
	QTY_OK_TSO_INCUT_MONTH  integer ,    
	QTY_P24_INCUT_MONTH integer ,    
	QTY_OK_P24_INCUT_MONTH  integer ,    
	QTY_OUT_EMAIL_MONTH integer ,    
	QTY_DELIV_OUT_EMAIL_MONTH   integer ,    
	QTY_IN_CALL_MONTH   integer ,    
	QTY_SMS_TA_ALL_MONTH    integer ,    
	QTY_IVR_MONTH   integer ,    
	QTY_OK_IVR_MONTH    integer ,    
	QTY_IN_CALL_SOFT_MONTH  integer ,    
	QTY_OUT_CALL_SOFT_MONTH integer ,    
	QTY_OK_OUT_CALL_SOFT_MONTH  integer ,    
	QTY_OK_PERS_OUT_CALL_SOFT_MONTH integer ,    
	QTY_CALL_RELTV_MONTH    integer ,    
	QTY_CALL_OK_PAY_MONTH   integer ,    
	QTY_CALL_OK_RELTV_PAY_MONTH integer ,    
	QTY_CALL_NO_PAY_MONTH   integer ,    
	QTY_CALL_3700_MONTH integer ,    
	QTY_CALL_BACK_MONTH integer ,    
	QTY_BOK_MONTH   integer ,    
	FL_COMM_60_033548   char(1) ,    
	FL_COMM_60_014802   char(1) ,    
	FL_COMM_60_036899   char(1) ,    
	FL_COMM_60_013648   char(1) ,    
	FL_COMM_60_017986   char(1) ,    
	FL_COMM_60_017953   char(1) ,  
		-- from SAS.SCORE_CLID_TRAN_DATA_RP  
		BBN_BNMN                char(2),
		QTY_BN_BIPL integer ,    
		AMT_BN_BIPL numeric(15  ,   2),
		FEE_BN_BIPL numeric(15  ,   2),
		QTY_N_BIPL  integer ,    
		AMT_N_BIPL  numeric(15  ,   2),
		FEE_N_BIPL  numeric(15  ,   2),
		QTY_R_PAYS  integer ,    
		AMT_R_PAYS  numeric(15  ,   2),
		FEE_R_PAYS  numeric(15  ,   2),
		QTY_EXPRESS integer ,    
		AMT_EXPRESS numeric(15  ,   2),
		FEE_EXPRESS numeric(15  ,   2),
		QTY_MOB integer ,    
		QTY_P24 integer ,    
		AMT_P24 numeric(15  ,   2),
		FEE_P24 numeric(15  ,   2),
		QTY_CR_POG  integer ,    
		AMT_CR_POG  numeric(15  ,   2),
		AMT_MOB numeric(15  ,   2),
		QTY_MOB_MB  integer ,    
		AMT_MOB_MB  numeric(15  ,   2),
		QTY_PHPAY_3700  integer ,    
		AMT_PHPAY_3700  numeric(15  ,   2),
		FEE_PHPAY_3700  numeric(15  ,   2),
		QTY_EX_BUY  integer ,    
		AMT_EX_BUY  numeric(15  ,   2),
		QTY_EX_SALE integer ,    
		AMT_EX_SALE numeric(15  ,   2),
		QTY_EX_CONV integer ,    
		AMT_EX_CONV numeric(15  ,   2),
		QTY_TRANSF_RECEIVE  integer ,    
		AMT_TRANSF_RECEIVE  numeric(15  ,   2),
		QTY_TRANSF_RECEIVE_CURR integer ,    
		AMT_TRANSF_RECEIVE_CURR numeric(15  ,   2),
		QTY_TRANSF_SENT integer ,    
		AMT_TRANSF_SENT numeric(15  ,   2),
		QTY_TRANSF_SENT_CURR    integer ,    
		AMT_TRANSF_SENT_CURR    numeric(15  ,   2),
		QTY_TRANSF_WU   integer ,    
		QTY_TRANSF_UNI  integer ,    
		QTY_TRANSF_GLD_CRW  integer ,    
		QTY_TRANSF_MG   integer ,    
		AMT_INSUR_NS    numeric(15  ,   2),
		AMT_INSUR_TI    numeric(15  ,   2),
		AMT_INSUR_NB    numeric(15  ,   2),
		AMT_INSUR_OS    numeric(15  ,   2),
		AMT_INSUR_CAS   numeric(15  ,   2),
		AMT_INSUR_ACDNT numeric(15  ,   2),
		AMT_INSUR_CAS_NPB   numeric(15  ,   2),
		AVG_AMT_DB_TARG numeric(15  ,   2),
		AVG_AMT_DB_NOT_TARG numeric(15  ,   2),
		QTY_POS_CR_PAN  numeric(15  ,   2),
		AVG_AMT_POS_CR_PAN  numeric(15  ,   2),
		AVG_AMT_POS_NCR_PAN numeric(15  ,   2),
		AVG_AMT_KOPL_CR numeric(15  ,   2),
		QTY_P24_ENTR    numeric(15  ,   2),
		AVG_QTY_P24_TRAN_P2P    numeric(15  ,   2),
		QTY_POS_TRAN    integer ,    
		AMT_POS_TRAN    numeric(15  ,   2),
		QTY_BN_TRAN integer ,    
		AMT_BN_TRAN numeric(15  ,   2),
		QTY_CASH_TRAN   integer ,    
		AMT_CASH_TRAN   numeric(15  ,   2),
		QTY_AUTO_TRAN   integer ,    
		AMT_AUTO_TRAN   numeric(15  ,   2),
		QTY_HA_TRAN integer ,    
		AMT_HA_TRAN numeric(15  ,   2),
		QTY_GOODS_TRAN  integer ,    
		AMT_GOODS_TRAN  numeric(15  ,   2),
		QTY_TREVEL_TRAN integer ,    
		AMT_TREVEL_TRAN numeric(15  ,   2),
		QTY_LINK_TRAN   integer ,    
		AMT_LINK_TRAN   numeric(15  ,   2),
		QTY_SERVICE_TRAN    integer ,    
		AMT_SERVICE_TRAN    numeric(15  ,   2),
		QTY_SHOP_TRAN   integer ,    
		AMT_SHOP_TRAN   numeric(15  ,   2),
		QTY_MED_TRAN    integer ,    
		AMT_MED_TRAN    numeric(15  ,   2),
		QTY_RPR_TRAN    integer ,    
		AMT_PRP_TRAN    numeric(15  ,   2),
		QTY_JEW_TRAN    integer ,    
		AMT_JEW_TRAN    numeric(15  ,   2),
		QTY_REST_VISIT  integer ,    
		AVG_REST_CHECK  numeric(15  ,   2),
		QTY_FOREIGN_TRAN    integer ,    
		AMT_FOREIGN_TRAN    numeric(15  ,   2),
		QTY_INTERNET_TRAN   integer ,    
		AMT_INTERNET_TRAN   numeric(15  ,   2),
		QTY_SWIFT_SENT  integer ,    
		AMT_SWIFT_SENT  numeric(15  ,   2),
		QTY_SWIFT_RES   integer ,    
		AMT_SWIFT_RES   numeric(15  ,   2),
		QTY_P2P_SENT    integer ,    
		AMT_P2P_SENT    numeric(15  ,   2),
		QTY_P2P_RES integer ,    
		AMT_P2P_RES numeric(15  ,   2),
		QTY_NBU_SENT    integer ,    
		AMT_NBU_SENT    numeric(15  ,   2),
		QTY_PS_CASS integer ,    
		AMT_PS_CASS numeric(15  ,   2),
		QTY_PS_TSO  integer ,    
		AMT_PS_TSO  numeric(15  ,   2),
		QTY_NOTR    integer ,    
		AMT_NOTR    numeric(15  ,   2),
		FEE_NOTR    numeric(15  ,   2),
		QTY_NOTR_REG_PROP   integer ,    
		AMT_NOTR_REG_PROP   numeric(15  ,   2),
		QTY_NOTR_SALE_PROP  integer ,    
		AMT_NOTR_SALE_PROP  numeric(15  ,   2),
		AMT_NOTR_TAX_ON_INCOME  numeric(15  ,   2),
		QTY_POS_SPECIAL integer ,    
		AMT_POS_SPECIAL numeric(15  ,   2),
		AVG_POS_SPECIAL numeric(15  ,   2),
		QTY_DAYS_MAX_TRAN_POS_SPECIAL   integer ,    
		QTY_CNA_INTERNET    integer ,    
		AMT_CNA_INTERNET    numeric(15  ,   2),
		QTY_TOP10_CNA_INTERNET  integer ,    
		AMT_TOP10_CNA_INTERNET  numeric(15  ,   2),
		QTY_FOREIGN_INTERNET    integer ,    
		AMT_FOREIGN_INTERNET    numeric(15  ,   2),
		QTY_FORGOT_PAN_ATM  integer ,    
		QTY_FORGOT_P24_PWD  integer ,    
		QTY_FORGOT_PIN  integer ,    
		QTY_LOST_PAN    integer ,    
		CALC_DATE   date    ,    
		AMT_PROFIT_UNI_GOLD numeric(15  ,   2),
		AVG_SALDO_UNI_GOLD  numeric(15  ,   2),
		ECA_BRNM2_TRAN_REAL char(4) ,    
		QTY_M_P24_LEDATE    integer ,    
		QTY_M_DATE_FIRST_DEPOS  integer ,    
		QTY_BN_BIPL_MONTH   integer ,    
		AMT_BN_BIPL_MONTH   numeric(15  ,   2),
		FEE_BN_BIPL_MONTH   numeric(15  ,   2),
		QTY_N_BIPL_MONTH    integer ,    
		AMT_N_BIPL_MONTH    numeric(15  ,   2),
		FEE_N_BIPL_MONTH    numeric(15  ,   2),
		QTY_R_PAYS_MONTH    integer ,    
		AMT_R_PAYS_MONTH    numeric(15  ,   2),
		FEE_R_PAYS_MONTH    numeric(15  ,   2),
		QTY_EXPRESS_MONTH   integer ,    
		AMT_EXPRESS_MONTH   numeric(15  ,   2),
		FEE_EXPRESS_MONTH   numeric(15  ,   2),
		QTY_MOB_MONTH   integer ,    
		QTY_P24_MONTH   integer ,    
		AMT_P24_MONTH   numeric(15  ,   2),
		FEE_P24_MONTH   numeric(15  ,   2),
		QTY_CR_POG_MONTH    integer ,    
		AMT_CR_POG_MONTH    numeric(15  ,   2),
		AMT_MOB_MONTH   numeric(15  ,   2),
		QTY_MOB_MB_MONTH    integer ,    
		AMT_MOB_MB_MONTH    numeric(15  ,   2),
		QTY_PHPAY_3700_MONTH    integer ,    
		AMT_PHPAY_3700_MONTH    numeric(15  ,   2),
		FEE_PHPAY_3700_MONTH    numeric(15  ,   2),
		QTY_EX_BUY_MONTH    integer ,    
		AMT_EX_BUY_MONTH    numeric(15  ,   2),
		QTY_EX_SALE_MONTH   integer ,    
		AMT_EX_SALE_MONTH   numeric(15  ,   2),
		QTY_EX_CONV_MONTH   integer ,    
		AMT_EX_CONV_MONTH   numeric(15  ,   2),
		QTY_TRANSF_RECEIVE_MONTH    integer ,    
		AMT_TRANSF_RECEIVE_MONTH    numeric(15  ,   2),
		QTY_TRANSF_RECEIVE_CURR_MONTH   integer ,    
		AMT_TRANSF_RECEIVE_CURR_MONTH   numeric(15  ,   2),
		QTY_TRANSF_SENT_MONTH   integer ,    
		AMT_TRANSF_SENT_MONTH   numeric(15  ,   2),
		QTY_TRANSF_SENT_CURR_MONTH  integer ,    
		AMT_TRANSF_SENT_CURR_MONTH  numeric(15  ,   2),
		QTY_TRANSF_WU_MONTH integer ,    
		QTY_TRANSF_UNI_MONTH    integer ,    
		QTY_TRANSF_GLD_CRW_MONTH    integer ,    
		QTY_TRANSF_MG_MONTH integer ,    
		AMT_INSUR_NS_MONTH  numeric(15  ,   2),
		AMT_INSUR_TI_MONTH  numeric(15  ,   2),
		AMT_INSUR_NB_MONTH  numeric(15  ,   2),
		AMT_INSUR_OS_MONTH  numeric(15  ,   2),
		AMT_INSUR_CAS_MONTH numeric(15  ,   2),
		AMT_INSUR_ACDNT_MONTH   numeric(15  ,   2),
		AMT_INSUR_CAS_NPB_MONTH numeric(15  ,   2),
		AVG_AMT_DB_TARG_MONTH   numeric(15  ,   2),
		AVG_AMT_DB_NOT_TARG_MONTH   numeric(15  ,   2),
		QTY_POS_CR_PAN_MONTH    integer ,    
		QTY_P24_ENTR_MONTH  integer ,    
		AVG_QTY_P24_TRAN_P2P_MONTH  numeric(15  ,   2),
		QTY_POS_TRAN_MONTH  integer ,    
		AMT_POS_TRAN_MONTH  numeric(15  ,   2),
		QTY_BN_TRAN_MONTH   integer ,    
		AMT_BN_TRAN_MONTH   numeric(15  ,   2),
		QTY_CASH_TRAN_MONTH integer ,    
		AMT_CASH_TRAN_MONTH numeric(15  ,   2),
		QTY_AUTO_TRAN_MONTH integer ,    
		AMT_AUTO_TRAN_MONTH numeric(15  ,   2),
		QTY_HA_TRAN_MONTH   integer ,    
		AMT_HA_TRAN_MONTH   numeric(15  ,   2),
		QTY_GOODS_TRAN_MONTH    integer ,    
		AMT_GOODS_TRAN_MONTH    numeric(15  ,   2),
		QTY_TREVEL_TRAN_MONTH   integer ,    
		AMT_TREVEL_TRAN_MONTH   numeric(15  ,   2),
		QTY_LINK_TRAN_MONTH integer ,    
		AMT_LINK_TRAN_MONTH numeric(15  ,   2),
		QTY_SERVICE_TRAN_MONTH  integer ,    
		AMT_SERVICE_TRAN_MONTH  numeric(15  ,   2),
		QTY_SHOP_TRAN_MONTH integer ,    
		AMT_SHOP_TRAN_MONTH numeric(15  ,   2),
		QTY_MED_TRAN_MONTH  integer ,    
		AMT_MED_TRAN_MONTH  numeric(15  ,   2),
		QTY_RPR_TRAN_MONTH  integer ,    
		AMT_PRP_TRAN_MONTH  numeric(15  ,   2),
		QTY_JEW_TRAN_MONTH  integer ,    
		AMT_JEW_TRAN_MONTH  numeric(15  ,   2),
		QTY_REST_VISIT_MONTH    integer ,    
		QTY_FOREIGN_TRAN_MONTH  integer ,    
		AMT_FOREIGN_TRAN_MONTH  numeric(15  ,   2),
		QTY_INTERNET_TRAN_MONTH integer ,    
		AMT_INTERNET_TRAN_MONTH numeric(15  ,   2),
		QTY_NBU_SENT_MONTH  integer ,    
		AMT_NBU_SENT_MONTH  numeric(15  ,   2),
		QTY_PS_CASS_MONTH   integer ,    
		AMT_PS_CASS_MONTH   numeric(15  ,   2),
		QTY_PS_TSO_MONTH    integer ,    
		AMT_PS_TSO_MONTH    numeric(15  ,   2),
		QTY_POS_SPECIAL_MONTH   integer ,    
		AMT_POS_SPECIAL_MONTH   numeric(15  ,   2),
		AVG_POS_SPECIAL_MONTH   numeric(15  ,   2),
		QTY_DAYS_MAX_TRAN_POS_SPEC_M    integer ,    
		QTY_CNA_INTERNET_MONTH  integer ,    
		AMT_CNA_INTERNET_MONTH  numeric(15  ,   2),
		QTY_TOP10_CNA_INTERNET_MONTH    integer ,    
		AMT_TOP10_CNA_INTERNET_MONTH    numeric(15  ,   2),
		QTY_FOREIGN_INTERNET_MONTH  integer ,    
		AMT_FOREIGN_INTERNET_MONTH  numeric(15  ,   2),
		AMT_PROFIT_UNI_GOLD_MONTH   numeric(15  ,   2),
		AVG_SALDO_UNI_GOLD_MONTH    numeric(15  ,   2),
		AVG_DBONLINECR_TO_DBALLCR_6M    numeric(15  ,   2),
		AVG_CRDB_TO_CRLIM_6M    numeric(15  ,   2),
		AVG_DBCASH_TO_CRLIM_6M  numeric(15  ,   2),
		AVG_DBPOS_TO_CRLIM_6M   numeric(15  ,   2),
		AVG_DBOTHER_TO_CRLIM_6M numeric(15  ,   2),
		AVG_DBCASH_6M   numeric(15  ,   2),
		QTY_MONTH_DB_ALL_6M integer ,    
		QTY_MONTH_TRAN_CR_ALL_6M    integer ,    
		RAT_DBATM_TO_DBALL_6M   numeric(15  ,   2),
		RAT_DBOTHER_TO_DBALL_6M numeric(15  ,   2),
		RAT_DBSALE_TO_DBALL_6M  numeric(15  ,   2),
		RAT_CRALL_TO_MINPAY_6M  numeric(15  ,   2),
		RAT_DBALL_TO_CRALL_6M   numeric(15  ,   2),
		RAT_DBPOS_TO_DBALL_6M   numeric(15  ,   2),
		QTY_TRAN_CRONLINE_6M    numeric(15  ,   2),
		QTY_TRAN_CRRS_6M    numeric(15  ,   2),
		QTY_TRAN_DBALL_6M   numeric(15  ,   2),
		QTY_TRAN_DBCASH_6M  numeric(15  ,   2),
		QTY_TRAN_DBOTHER_6M numeric(15  ,   2),
		QTY_DBSALE_6M   numeric(15  ,   2),
		AMT_CRCELLSALARY_6M numeric(15  ,   2),
		AMT_CR_NOTCELLSALARY_6M numeric(15  ,   2),
		AMT_DB_CRCARDS_6M   numeric(15  ,   2),
		AMT_DBONLINE_CRCARDS_6M numeric(15  ,   2),
		AMT_TRANCRRS_6M numeric(15  ,   2),
		AMT_TRAN_DBALL_6M   numeric(15  ,   2),
		AMT_TRAN_DBCASH_6M  numeric(15  ,   2),
		AMT_TRAN_DBOTHER_6M numeric(15  ,   2),
		AMT_TRAN_POSDB_6M   numeric(15  ,   2),
		AMT_LAST_REPAYMENT  numeric(15  ,   2),
		QTY_CR_CRED_PAN_LM  integer ,    
		QTY_D_P24_LEDATE    integer ,    
		QTY_D_FIRST_DEPOS   integer ,    
		RAT_TRAN_FOOD_12M   numeric(15  ,   2),
		QTY_MCC_12M integer ,    
		AVG_PAYPART_DAYS    numeric(15  ,   2),
		AVG_PAYPART_SUM numeric(15  ,   2),
		QTY_SHOPS   integer ,    
		QTY_DB_BPLUS_TRAN_MONTH integer ,    
		AMT_DB_BPLUS_TRAN_MONTH numeric(15  ,   2),
		QTY_DB_BPLUS_TRAN_6M    integer ,    
		AMT_DB_BPLUS_TRAN_6M    numeric(15  ,   2),
		QTY_CLEAR_POS_TRAN_12M  integer ,    
		QTY_CLEAR_POS_TRAN_6M   integer ,    
		QTY_CLEAR_POS_TRAN_SAL_PAN_12M  integer ,    
		QTY_CLEAR_POS_TRAN_SAL_PAN_6M   integer ,    
		QTY_CLEAR_POS_TRAN_CR_PAN_12M   integer ,    
		QTY_CLEAR_POS_TRAN_CR_PAN_6M    integer ,    
		AMT_CHARIT_12M  numeric(15  ,   2),
		REP_QTY_DISC_30 integer ,    
		REP_AMT_TRAN_DISC_30    numeric(15  ,   2),
		REP_AMT_DISC_30 numeric(15  ,   2),
		REP_QTY_DISC_3M integer ,    
		REP_AMT_TRAN_DISC_3M    numeric(15  ,   2),
		REP_AMT_DISC_3M numeric(15  ,   2),
		REP_QTY_DISC_6M integer ,    
		REP_AMT_TRAN_DISC_6M    numeric(15  ,   2),
		REP_AMT_DISC_6M numeric(15  ,   2),
		QTY_ATM_CASH_PB integer ,    
		AMT_ATM_CASH_PB numeric(15  ,   2),
		QTY_ATM_CASH_OTHER  integer ,    
		AMT_ATM_CASH_OTHER  numeric(15  ,   2),
		FL_SALE_RENT_INCOME char(1) ,    
		AMT_TRANSF_RECEIVE_3_MONTH  numeric(15  ,   2),
		AMT_TRANSF_RECEIVE_CURR_3_MONTH numeric(15  ,   2),
		FL_REMITTANCE_3_MONTH   char(1) ,    
		FL_AID  char(1) ,    
		AMT_DB_3_MONTH  numeric(15  ,   2),
		AMT_CR_3_MONTH  numeric(15  ,   2),
		AMT_OBOROT_GROUP    smallint    ,    
		RISK_GEOGR  char(1) ,    
		P24_WEB_ENTRY_QTY   integer ,    
		P24_MOB_ENTRY_QTY   integer ,    
		P24_WEB_ENTRY_1M    integer ,    
		P24_MOB_ENTRY_1M    integer ,    
		P24_WEB_DAY_1M  integer ,    
		P24_MOB_DAY_1M  integer ,    
		P24_WEB_ENTRY_6M    integer ,    
		P24_MOB_ENTRY_6M    integer ,    
		P24_WEB_DAY_6M  integer ,    
		P24_MOB_DAY_6M  integer ,    
		P24_WEB_TEACH_QTY   integer ,    
		P24_MOB_TEACH_QTY   integer ,    
		P24_WEB_TEACH_1M    integer ,    
		P24_MOB_TEACH_1M    integer ,    
		P24_WEB_TEACH_6M    integer ,    
		P24_MOB_TEACH_6M    integer ,   
		INT_PAYM                       	char(1) NULL,
		FL_INCOME_GIFT                 	char(1) NULL,
		GET_VAR_CASH                   	char(1) NULL,
		PUT_VAR_CASH                   	integer NULL,
		QTY_CASH_WO_PAN_AL             	integer NULL,
		QTY_CASH_WO_PAN_1M             	integer NULL,
		QTY_CASH_WO_PAN_3M             	integer NULL,
		QTY_CASH_WO_PAN_6M             	integer NULL,
		QTY_P24_SHOP_1M                	integer NULL,
		AMT_P24_SHOP_1M                	numeric(15,2) NULL,
		QTY_P24_SHOP_3M                	integer NULL,
		AMT_P24_SHOP_3M                	numeric(15,2) NULL,
		QTY_P24_SHOP_6M                	integer NULL,
		AMT_P24_SHOP_6M                	numeric(15,2) NULL,
		QTY_P24_SHOP_12M               	integer NULL,
		AMT_P24_SHOP_12M               	numeric(15,2) NULL,
		QTY_P24_ENTER_ALL_1M           	integer NULL,
		PERC_P24_ENTER_NT_1M           	numeric(15,2) NULL,
		PERC_P24_ENTER_NT_6M           	numeric(15,2) NULL,
		QTY_DEVICE_1M                  	integer NULL,
		QTY_DEVICE_3M                  	integer NULL,
		QTY_DEVICE_6M                  	integer NULL,
		FIN_DOP_IRRETRIEVABLY          	char(1) NULL,
		FL_PDV                         	char(1) NULL,
		GET_CASH_75						char(1) NULL  